version: '3.2'
services:
  server:
    image: doctest3
    ports:
      - 80:8080
    environment:
      # - GET_ENV_RESPONSE=set-params
      - FILE_RES_PATH=./var/
      # - CON_PORT=8080
    volumes:
      - ./var:/var
    command: >
      node ./index.js